### ISSUE TITLE
Sort Order 

### ISSUE THREAD

**Issue by baamf** [archiecobbs/logwarn#24]
Love the logwarn utility, but have been receiving some matches of some old logs when coupled with Nagios.  Through a little troubleshooting, I believe it is caused by the sort order and rotation.  When my messages files are rotated they use a date method (i.e. messages, messages-20150802, messages-20150809, messages-20150816).  After the rotate the first file in the sort (messages-20150802) is checked, rather than the newest file (messages-20150816).  Is this something easily modified?  Still poking around on the wiki and what not to see if i am missing something.  Please let me know.  Thanks.

**Comment by archiecobbs** [comment]
You are exactly right. Sort order should be reversed when the suffix contains a formatted timestamp.

Fixed by ded059b, which adds a `-R` flag for this.
