### ISSUE TITLE
distribute bootstrapped tarballs.

### ISSUE THREAD

**Issue by andreasstieger** [archiecobbs/logwarn#25]
Please distribute bootstrapped tarballs (e.g. containing the configure script) with your releases by attaching them to the corresponding tag as a binary asset.

**Comment by archiecobbs** [comment]
They are distributed, it's just not obvious where to get them.

See https://github.com/archiecobbs/logwarn/wiki/Downloads

I'll also put a link on the main README.

Thanks.
