### ISSUE TITLE
Case insensitive regex not supported

### ISSUE THREAD

**Issue by ranvijayj** [archiecobbs/logwarn#27]
"^.*(error|failure|connection|timeout).*$/i"

**Comment by archiecobbs** [comment]
That looks like Javascript regular expression syntax. There is no Javascript here.

`logwarn` uses UNIX extended regular expression syntax, described [here](https://www.freebsd.org/cgi/man.cgi?query=re_format&sektion=7).

**Comment by ranvijayj** [comment]
Can you please help me with case insensitive matching?  @archiecobbs

**Comment by archiecobbs** [comment]
Not supported currently.

I'll consider this a feature request.

**Comment by archiecobbs** [comment]
Oops, I forgot, this is supported. Use the `-c` flag for case-insensitive matching.

See the [ManPage](https://github.com/archiecobbs/logwarn/wiki/ManPage) for details.
