### ISSUE TITLE
Gives warning even if pattern does not match

### ISSUE THREAD

**Issue by ranvijayj** [archiecobbs/logwarn#28]
Hi, 

I am using this to check on a remote host using below command

`/usr/local/nagios/libexec/check_by_ssh -H IP -t 30 -C '/usr/lib/nagios/plugins/check_logwarn  -f  /home/ubuntu/nagios_log_tracker/events.txt /home/ubuntu/events.txt  "^.*(rror|ERROR|ailure|onnection|imeout|xception).*$" '
OK: No log errors found`

Here I get output OK. But on Nagios it throws a warning Yellow. It shows all lines.

I used -p and -c and -m as well. But did not help. 

What could be the reason? Let me know if you need more details.

**Comment by ranvijayj** [comment]
On Nagios UI


> Current Status: | WARNING   (for 0d 0h 0m 10s)
> -- | --
> Status Information: | Log errors: Starting as ubuntu
> Performance Data: |  
> Current Attempt: | 1/1  (HARD state)
> Last Check Time: | 08-21-2018 13:16:05
> Check Type: | ACTIVE
> Check Latency / Duration: | 0.000 / 0.768 seconds
> Next Scheduled Check: | 08-21-2018 13:19:05
> Last State Change: | 08-21-2018 13:16:00
> Last Notification: | N/A (notification 0)
> Is This Service Flapping? | YES   (47.50% state change)
> In Scheduled Downtime? | NO
> Last Update: | 08-21-2018 13:16:06  ( 0d 0h 0m 4s ago)

**Comment by ranvijayj** [comment]
Does not match pattern

**Comment by archiecobbs** [comment]
Did you configure Nagios properly according to [Nagios Configuration](https://github.com/archiecobbs/logwarn/wiki/NagiosPlugin#nagios-configuration)?

Also, why are you adding `OK: No log errors found` to the command line? Don't do that.

**Comment by ranvijayj** [comment]
Hey 

`OK: No log errors found` was the output..

Anyways I added `! ".*"` after the pattern and I think it is working now. Without that it gives warning for any string...
I will try an update the docs and raise a PR...

But yeah one last thing...... it still gives Warning for pattern match and not critical...

**Comment by ranvijayj** [comment]
@archiecobbs

**Comment by archiecobbs** [comment]
From the second sentence on the man page:

> A line that matches neither a positive nor a negative pattern is considered a match (use the -p flag to change this default).

**Comment by archiecobbs** [comment]
Also, there should be no space between `!` and the negative pattern.

**Comment by archiecobbs** [comment]
That would require a change to the plugin. I'll make it a feature request.

**Comment by archiecobbs** [comment]
Fixed in 68c5b2a.
