### ISSUE TITLE
Bug: inifinite loop with -C option

### ISSUE THREAD

**Issue by regilero** [archiecobbs/logwarn#29]
I you use the new -C option (to get a CRITICAL and not WARNING exit code) you'll end up in an inifnite loop with growing CPU usage.

Lacking the 'next argument parsing' command in check_logwarn.in:

```
    -C)
        MATCH_RETURN="${STATE_CRITICAL}"
        ;;
```

Should be:

```
    -C)
        MATCH_RETURN="${STATE_CRITICAL}"
        unset PLUGIN_ARGS[$FIRST_KEY]
        ;;
```

**Comment by archiecobbs** [comment]
Thanks! Should be fixed in b292ee1.
